services:
  producer:
    container_name: producer
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080    
    ports:
      - "5000:8080" 
    networks:
      - app-network
    depends_on:
      - rabbitmq
    
  rabbitmq:    
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
       - app-network
